### ISSUE TITLE
Snowpack requires one output

### ISSUE THREAD

**Issue by luastoned** [awu43/snowpack-start#2]
Install works fine now, but after doing

```
cd snowpack
yarn start
```

the following error appears:

```
Quickstart:

  cd snowpack
  yarn start

All Commands:

  yarn start       Start your development server.
  yarn build       Build your website for production.
  yarn test        Run your tests.

13:14:48 /code/node/starter-kits > cd snowpack
13:14:55 /code/node/starter-kits/snowpack (master) > yarn start
yarn run v1.22.5
$ snowpack dev
[14:15:59] [snowpack] Error: Requires one output.

Error: Requires one output.
    at buildScriptPlugin (/code/node/starter-kits/snowpack/node_modules/@snowpack/plugin-build-script/plugin.js:7:11)
    at execPluginFactory (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:53618:18)
    at loadPluginFromConfig (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:53631:22)
    at /code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:53655:24
    at Array.forEach (<anonymous>)
    at loadPlugins (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:53652:20)
    at normalizeConfig (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:53761:39)
    at createConfiguration (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:53982:30)
    at Object.loadConfiguration (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:54061:16)
    at async cli (/code/node/starter-kits/snowpack/node_modules/snowpack/lib/index.js:132040:22)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by andrew-1135** [comment]
This one I'm not sure where the problem is. Two things to try:

- Downgrade Snowpack from 3.1 to 3.0 (3.1 still has a ton of bugs).
- Try using `create-snowpack-app`.

If downgrading doesn't work but `create-snowpack-app` does, then the problem is on this end.

**Comment by aFuzzyBear** [comment]
Hi man, Im am having the same issue, tried downgrading to v3.0 with no avail. I really like the setup tho...

**Comment by andrew-1135** [comment]
That's not good 😬.

Did `create-snowpack-app` work?

**Comment by aFuzzyBear** [comment]
Hey man, the entire cli install was brilliant, it 'felt' like it did but then it was the latest version of snowpack and even when I rolled it back i still got nowhere...
I got a lot of hope for this wee repo man, good work with it, if I can help just let me know

**Comment by andrew-1135** [comment]
I recently added an issue template for bug reports, fill it out after opening a new issue and the information should help me find where the problem is.

**Comment by awu43** [comment]
@luastoned, @aFuzzyBear, either of you still there? I'd really like to resolve this issue.

**Comment by luastoned** [comment]
I used the latest version, still getting the same output.

**Comment by awu43** [comment]
After some experimenting, I believe the problem is with `@snowpack/plugin-build-script`. As the original error message (which I somehow overlooked for three months) says, you haven't specified any output files. Is there a particular reason you're using `@snowpack/plugin-build-script` and  `@snowpack/plugin-run-script`? They're not required for running Snowpack and are used when you need something beyond other available plugins.

**Comment by luastoned** [comment]
I'm doing nothing but `npx snowpack-start@latest --use-yarn` and `yarn start`
I never touched the code or anything in between.

**Comment by awu43** [comment]
Well, this was an unfortunate wild goose chase. Thanks for bringing it up though, definitely going to put a warning about those two plugins. On the bright side, this finally clears the way for a v1.0.0 release.
